stages:
    - Static Analysis
    - Unit Test
    - Build

.java_with_sbt:
    image: openjdk:8u292-jdk
    variables:
        SBT_VERSION: "1.5.2"
    before_script:
        - wget -O - https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz |
          gunzip |
          tar -x -C /usr/local
        - PATH=/usr/local/sbt/bin:${PATH}
        - cd scala

.python_with_pyright:
    image: nikolaik/python-nodejs:python3.7-nodejs12
    before_script:
        - npm install --global pyright

.docker_build:
    image: docker:19.03.15
    services:
        - docker:19.03.15-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - echo -n $DOCKER_REGISTRY_PASSWORD |
          docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY

scalastyle:
    stage: Static Analysis
    extends:
        - .java_with_sbt
    script:
        - sbt
          core/scalastyle
          dataBroker/scalastyle
          gitlabFetcher/scalastyle
          aPlusFetcher/scalastyle
          coreAdapter/scalastyle
          gitlabAdapter/scalastyle
          adapterCourse/scalastyle
          adapterGeneralModel/scalastyle
          adapterDataset/scalastyle

scapegoat:
    stage: Static Analysis
    extends:
        - .java_with_sbt
    script:
        - sbt
          core/scapegoat
          dataBroker/scapegoat
          gitlabFetcher/scapegoat
          aPlusFetcher/scapegoat
          coreAdapter/scapegoat
          gitlabAdapter/scapegoat
          adapterCourse/scapegoat
          adapterGeneralModel/scapegoat
          adapterDataset/scapegoat
    artifacts:
        when: always
        reports:
            junit:
                - /builds/cs/VISDOM/data-management-system/scala/core/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/broker/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/gitlab-fetcher/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/aplus-fetcher/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/core-adapter/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/gitlab-adapter/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/adapter-course/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/adapter-general-model/target/scala-2.12/scapegoat-report/scapegoat.xml
                - /builds/cs/VISDOM/data-management-system/scala/adapter-dataset/target/scala-2.12/scapegoat-report/scapegoat.xml

pyright:
    stage: Static Analysis
    extends:
        - .python_with_pyright
    script:
        - cd python/dataset-fetcher
        - python3 -m pip install -r requirements.txt
        - pyright --pythonplatform Linux --pythonversion 3.7 --lib --stats .

unit_test:
    stage: Unit Test
    extends:
        - .java_with_sbt
    script:
        - sbt
          core/test
    artifacts:
        when: always
        reports:
            junit:
                - /builds/cs/VISDOM/data-management-system/scala/core/target/TEST*.xml

build_images:
    stage: Build
    extends:
        - .docker_build
    script:
        - sh build_image.sh mongodb-initializer Dockerfile-init mongodb/utility-scripts true
        - sh build_image.sh broker Dockerfile-broker scala false
        - sh build_image.sh fetcher-gitlab Dockerfile-fetcher-gitlab scala false
        - sh build_image.sh fetcher-aplus Dockerfile-fetcher-aplus scala false
        - sh build_image.sh fetcher-dataset Dockerfile python/dataset-fetcher true
        - sh build_image.sh adapter-gitlab Dockerfile-adapter-gitlab scala false
        - sh build_image.sh adapter-course Dockerfile-adapter-course scala false
        - sh build_image.sh adapter-general-model Dockerfile-adapter-general-model scala false
        - sh build_image.sh adapter-dataset Dockerfile-adapter-dataset scala false
