stages:
    - Static Analysis
    - Unit Test
    - Build

.java_with_sbt:
    image: openjdk:8u292-jdk
    variables:
        SBT_VERSION: "1.5.2"
    before_script:
        - wget -O - https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz |
          gunzip |
          tar -x -C /usr/local
        - PATH=/usr/local/sbt/bin:${PATH}
        - cd scala

.docker_build:
    image: docker:19.03.15
    services:
        - docker:19.03.15-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - cd scala

scalastyle:
    stage: Static Analysis
    extends:
        - .java_with_sbt
    script:
        - sbt core/scalastyle
        - sbt dataBroker/scalastyle
        - sbt gitlabFetcher/scalastyle
        - sbt aPlusFetcher/scalastyle
        - sbt gitlabAdapter/scalastyle

scapegoat:
    stage: Static Analysis
    extends:
        - .java_with_sbt
    script:
        - sbt core/scapegoat
        - sbt dataBroker/scapegoat
        - sbt gitlabFetcher/scapegoat
        - sbt aPlusFetcher/scapegoat
        - sbt gitlabAdapter/scapegoat

unit_test:
    stage: Unit Test
    extends:
        - .java_with_sbt
    script:
        - sbt core/test
        - sbt dataBroker/test
        - sbt gitlabFetcher/test
        - sbt aPlusFetcher/test
        - sbt gitlabAdapter/test

broker:
    stage: Build
    extends:
        - .docker_build
    script:
        - docker build
          --tag visdom-broker:test
          --file Dockerfile-broker
          .

fetcher_gitlab:
    stage: Build
    extends:
        - .docker_build
    script:
        - docker build
          --tag visdom-fetcher-gitlab:test
          --file Dockerfile-fetcher-gitlab
          .

fetcher_aplus:
    stage: Build
    extends:
        - .docker_build
    script:
        - docker build
          --tag visdom-fetcher-aplus:test
          --file Dockerfile-fetcher-aplus
          .

adapter_gitlab:
    stage: Build
    extends:
        - .docker_build
    script:
        - docker build
          --tag visdom-adapter-gitlab:test
          --file Dockerfile-adapter-gitlab
          .
