# Copyright 2022 Tampere University
# This software was developed as a part of the VISDOM project: https://iteavisdom.org/
# This source code is licensed under the MIT license. See LICENSE in the repository root directory.
# Author(s): Ville Heikkilä <ville.heikkila@tuni.fi>

version: '3.7'

services:
    spark-master:
        image: bde2020/spark-master:3.1.1-hadoop3.2
        container_name: ${SPARK_MASTER_HOST}
        expose:
            - 7077
        ports:
            - ${SPARK_MASTER_UI_PORT}:8080
        environment:
            - INIT_DAEMON_STEP=setup_spark
        networks:
            - spark-network

