# Copyright 2022 Tampere University
# This software was developed as a part of the VISDOM project: https://iteavisdom.org/
# This source code is licensed under the MIT license. See LICENSE in the repository root directory.
# Author(s): Ville Heikkilä <ville.heikkila@tuni.fi>

version: '3.7'

services:
    spark-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: visdom/spark-test-app:0.1
        container_name: visdom-spark-test-app
        ports:
            - 4040:4040
        environment:
            - APPLICATION_NAME=${APPLICATION_NAME}
            - ENABLE_INIT_DAEMON=false
            - SPARK_MASTER_NAME=${SPARK_MASTER_HOST}
            - SPARK_MASTER_PORT=7077
        networks:
            - visdom-spark-network

networks:
    visdom-spark-network:
        name: ${SPARK_NETWORK}
        external: true
