package visdom.http.server


object AttributeConstants {
    final val ActionType: String = "actionType"
    final val Allowed: String = "allowed"
    final val Database: String = "database"
    final val DateAfter: String = "dateAfter"
    final val DateBefore: String = "dateBefore"
    final val EndDate: String = "endDate"
    final val FilePath: String = "filePath"
    final val GitlabServer: String = "gitlabServer"
    final val IncludeCommitLinks: String = "includeCommitLinks"
    final val IncludeFileLinks: String = "includeFileLinks"
    final val IncludeJobs: String = "includeJobs"
    final val IncludeJobLogs: String = "includeJobLogs"
    final val IncludeReferenceLinks: String = "includeReferenceLinks"
    final val IncludeStatistics: String = "includeStatistics"
    final val IncludeReports: String = "includeReports"
    final val NotFound: String = "notFound"
    final val ProjectId: String = "projectId"
    final val ProjectName: String = "projectName"
    final val ProjectNames: String = "projectNames"
    final val Projects: String = "projects"
    final val Recursive: String = "recursive"
    final val Reference: String = "reference"
    final val SourceServer: String = "sourceServer"
    final val StartDate: String = "startDate"
    final val TargetType: String = "targetType"
    final val Unauthorized: String = "unauthorized"
    final val UseAnonymization: String = "useAnonymization"
    final val UserId: String = "userId"
}
