package visdom.utils


object AttributeConstants {
    val AdapterType: String = "adapterType"
    val ApiAddress: String = "apiAddress"
    val Allowed: String = "allowed"
    val ComponentName: String = "componentName"
    val Courses: String = "courses"
    val Database: String = "database"
    val EndDate: String = "endDate"
    val ExerciseGitLocations: String = "exerciseGitLocations"
    val FetcherType: String = "fetcherType"
    val FilePath: String = "filePath"
    val GitBranch: String = "gitBranch"
    val Id: String = "id"
    val Information: String = "information"
    val LateSubmissionCoefficient: String = "lateSubmissionCoefficient"
    val LateSubmissionDate: String = "lateSubmissionDate"
    val Links: String = "_links"
    val Metadata: String = "metadata"
    val Modules: String = "modules"
    val NotFound: String = "notFound"
    val Options: String = "options"
    val ProjectNames: String = "projectNames"
    val Projects: String = "projects"
    val Recursive: String = "recursive"
    val Reference: String = "reference"
    val SourceServer: String = "sourceServer"
    val StartDate: String = "startDate"
    val SwaggerDefinition: String = "swaggerDefinition"
    val Unauthorized: String = "unauthorized"
    val UseAnonymization: String = "useAnonymization"
    val Version: String = "version"
}
