package visdom.utils


object SnakeCaseConstants {
    val AdapterType: String = "adapter_type"
    val ApiAddress: String = "api_address"
    val ApplicationName: String = "application_name"
    val CommittedDate: String = "committed_date"
    val CommitterEmail: String = "committer_email"
    val Commits: String = "commits"
    val ComponentName: String = "component_name"
    val CourseId: String = "course_id"
    val Database: String = "database"
    val DisplayName: String = "display_name"
    val En: String = "en"
    val Exercises: String = "exercises"
    val FetcherType: String = "fetcher_type"
    val FullName: String = "full_name"
    val Git: String = "git"
    val GitlabServer: String = "gitlab_server"
    val Grade: String = "grade"
    val HostName: String = "host_name"
    val Id: String = "id"
    val Index: String = "index"
    val Information: String = "information"
    val IsFolder: String = "is_folder"
    val Links: String = "_links"
    val Message: String = "message"
    val Metadata: String = "metadata"
    val Modules: String = "modules"
    val Name: String = "name"
    val Number: String = "number"
    val Other: String = "other"
    val Path: String = "path"
    val ProjectName: String = "project_name"
    val Raw: String = "raw"
    val SourceServer: String = "source_server"
    val SubmissionData: String = "submission_data"
    val SubmissionTime: String = "submission_time"
    val SubmissionsWithPoints: String = "submissions_with_points"
    val SwaggerDefinition: String = "swagger_definition"
    val Version: String = "version"
}
