version: '3.7'

services:
    visdom-gitlab-adapter:
        build: .
        image: visdom/gitlab-adapter:1.0
        container_name: ${APPLICATION_NAME}
        ports:
            - ${HOST_PORT}:4000
        environment:
            - APPLICATION_NAME=${APPLICATION_NAME}
            - HOST_NAME=${HOST_NAME}
            - HOST_PORT=${HOST_PORT}
            - MONGODB_HOST=${MONGODB_HOST}
            - MONGODB_PORT=${MONGODB_PORT}
            - MONGODB_USERNAME=${MONGODB_USERNAME}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
            - MONGODB_DATABASE=${MONGODB_DATABASE}
            - MONGODB_METADATA_DATABASE=${MONGODB_METADATA_DATABASE}
        networks:
            - visdom-gitlab-adapter-network

networks:
    visdom-gitlab-adapter-network:
        name: ${ADAPTER_NETWORK}
        external: true
