version: '3.7'

services:
    adapter-general:
        build:
            context: ../../scala
            dockerfile: Dockerfile-adapter-general-model
        image: visdom/adapter-general:0.1
        container_name: ${APPLICATION_NAME}
        ports:
            - ${SPARK_PORT}:4040
            - ${HOST_PORT}:8080
        environment:
            - APPLICATION_NAME=${APPLICATION_NAME}
            - ENABLE_INIT_DAEMON=false
            - HOST_NAME=${HOST_NAME}
            - HOST_PORT=${HOST_PORT}
            - MONGODB_HOST=${MONGODB_HOST}
            - MONGODB_PORT=${MONGODB_PORT}
            - MONGODB_USERNAME=${MONGODB_USERNAME}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
            - MONGODB_METADATA_DATABASE=${MONGODB_METADATA_DATABASE}
            - GITLAB_DATABASE=${GITLAB_DATABASE}
            - APLUS_DATABASE=${APLUS_DATABASE}
            - CACHE_DATABASE=${CACHE_DATABASE}
            - SPARK_MASTER_NAME=${SPARK_MASTER_HOST}
            - SPARK_MASTER_PORT=7077
        networks:
            - visdom-network

networks:
    visdom-network:
        name: ${ADAPTER_NETWORK}
        external: true
