FROM openjdk:11.0.15-jdk AS builder

ENV SBT_VERSION 1.6.2
RUN wget -O - https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | gunzip | tar -x -C /usr/local
ENV PATH /usr/local/sbt/bin:${PATH}

RUN mkdir -p /builder/project
WORKDIR /builder

COPY build.sbt /builder/build.sbt
COPY project/build.properties /builder/project/build.properties
COPY project/plugins.sbt /builder/project/plugins.sbt

RUN mkdir -p /builder/core
COPY core/build.sbt /builder/core/build.sbt
RUN sbt core/update
COPY core/ /builder/core/
RUN sbt core/compile

RUN mkdir -p /builder/broker
COPY broker/build.sbt /builder/broker/build.sbt
RUN sbt dataBroker/update
COPY broker/ /builder/broker/
RUN sbt dataBroker/compile
RUN sbt dataBroker/assembly


FROM openjdk:11.0.15-jre-slim
COPY --from=builder /builder/broker/target/scala-2.12/broker-0.2.jar /broker-0.2.jar

# to ensure that log4j exploits cannot be used
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS true

CMD [ "java", "-jar", "/broker-0.2.jar" ]
