FROM openjdk:8u292-jdk AS builder

ENV SBT_VERSION 1.5.2
RUN wget -O - https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | gunzip | tar -x -C /usr/local
ENV PATH /usr/local/sbt/bin:${PATH}

RUN mkdir -p /builder/project
WORKDIR /builder

COPY build.sbt /builder/build.sbt
COPY project/build.properties /builder/project/build.properties
COPY project/plugins.sbt /builder/project/plugins.sbt

RUN mkdir -p /builder/core
COPY core/build.sbt /builder/core/build.sbt
RUN sbt core/update
COPY core/ /builder/core/
RUN sbt core/compile

RUN mkdir -p /builder/aplus-fetcher
COPY aplus-fetcher/build.sbt /builder/aplus-fetcher/build.sbt
RUN sbt aPlusFetcher/update
COPY aplus-fetcher/ /builder/aplus-fetcher/
RUN sbt aPlusFetcher/compile
RUN sbt aPlusFetcher/assembly


FROM openjdk:8u292-jre-slim
COPY --from=builder /builder/aplus-fetcher/target/scala-2.12/aplus-fetcher-0.2.jar /aplus-fetcher-0.2.jar

# to ensure that log4j exploits cannot be used
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS true

CMD [ "java", "-jar", "/aplus-fetcher-0.2.jar" ]
