FROM openjdk:11.0.15-jdk AS builder

ENV SBT_VERSION 1.6.2
RUN wget -O - https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | gunzip | tar -x -C /usr/local
ENV PATH /usr/local/sbt/bin:${PATH}

ENV BUILDER_FOLDER builder

RUN mkdir -p /${BUILDER_FOLDER}/project
WORKDIR /${BUILDER_FOLDER}

COPY build.sbt /${BUILDER_FOLDER}/build.sbt
COPY project/build.properties /${BUILDER_FOLDER}/project/build.properties
COPY project/plugins.sbt /${BUILDER_FOLDER}/project/plugins.sbt

ENV CORE_FOLDER core
ENV CORE_PROJECT core

RUN mkdir -p /${BUILDER_FOLDER}/core
COPY ${CORE_FOLDER}/build.sbt /${BUILDER_FOLDER}/${CORE_FOLDER}/build.sbt
RUN sbt ${CORE_PROJECT}/update
COPY ${CORE_FOLDER}/ /${BUILDER_FOLDER}/${CORE_FOLDER}/
RUN sbt ${CORE_PROJECT}/compile

ENV TARGET_FOLDER adapter-course
ENV TARGET_PROJECT adapterCourse

RUN mkdir -p /${BUILDER_FOLDER}/${TARGET_FOLDER}
COPY ${TARGET_FOLDER}/build.sbt /${BUILDER_FOLDER}/${TARGET_FOLDER}/build.sbt
RUN sbt ${TARGET_PROJECT}/update
COPY ${TARGET_FOLDER}/ /${BUILDER_FOLDER}/${TARGET_FOLDER}/
RUN sbt ${TARGET_PROJECT}/compile
RUN sbt ${TARGET_PROJECT}/assembly


FROM bde2020/spark-submit:3.1.1-hadoop3.2

# These should be the same as BUILDER_FOLDER and TARGET_FOLDER from above
# and SPARK_APPLICATION_VERSION has to match the to the version set in the project
ENV BUILDER_FOLDER builder
ENV SPARK_APPLICATION_NAME adapter-course
ENV SPARK_APPLICATION_VERSION 0.2

ENV SPARK_APPLICATION_MAIN_CLASS visdom.adapters.course.CourseAdapter
ENV SPARK_APPLICATION_ARGS ""

ENV SPARK_APPLICATION_JAR_NAME ${SPARK_APPLICATION_NAME}-${SPARK_APPLICATION_VERSION}.jar
ENV SPARK_APPLICATION_JAR_LOCATION /${SPARK_APPLICATION_JAR_NAME}

ENV SOURCE_JAR /${BUILDER_FOLDER}/${SPARK_APPLICATION_NAME}/target/scala-2.12/${SPARK_APPLICATION_NAME}-${SPARK_APPLICATION_VERSION}.jar
ENV TARGET_JAR /${SPARK_APPLICATION_NAME}-${SPARK_APPLICATION_VERSION}.jar

COPY --from=builder ${SOURCE_JAR} ${TARGET_JAR}

# to ensure that log4j exploits cannot be used
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS true

CMD [ "/submit.sh" ]
