FROM openjdk:8u292-jdk AS builder

ENV SBT_VERSION 1.5.2
RUN wget -O - https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz | gunzip | tar -x -C /usr/local
ENV PATH /usr/local/sbt/bin:${PATH}

RUN mkdir -p /builder/project
WORKDIR /builder

COPY build.sbt /builder/build.sbt
COPY project/build.properties /builder/project/build.properties
COPY project/plugins.sbt /builder/project/plugins.sbt

RUN mkdir -p /builder/core
COPY core/build.sbt /builder/core/build.sbt
RUN sbt core/update
COPY core/ /builder/core/
RUN sbt core/compile

RUN mkdir -p /builder/gitlab-adapter
COPY gitlab-adapter/build.sbt /builder/gitlab-adapter/build.sbt
RUN sbt gitlabAdapter/update
COPY gitlab-adapter/ /builder/gitlab-adapter/
RUN sbt gitlabAdapter/compile
RUN sbt gitlabAdapter/assembly


FROM bde2020/spark-submit:3.1.1-hadoop3.2
COPY --from=builder /builder/gitlab-adapter/target/scala-2.12/gitlab-adapter-0.2.jar /gitlab-adapter-0.2.jar

ENV SPARK_APPLICATION_NAME gitlab-adapter
ENV SPARK_APPLICATION_VERSION 0.2

ENV SPARK_APPLICATION_MAIN_CLASS visdom.adapter.gitlab.Adapter
ENV SPARK_APPLICATION_ARGS ""

ENV SPARK_APPLICATION_JAR_NAME ${SPARK_APPLICATION_NAME}-${SPARK_APPLICATION_VERSION}.jar
ENV SPARK_APPLICATION_JAR_LOCATION /${SPARK_APPLICATION_JAR_NAME}

CMD [ "/submit.sh" ]
