version: '3.7'

services:

    visdom-aplus-fetcher:
        build:
            context: ../../scala
            dockerfile: Dockerfile-fetcher-aplus
        image: visdom/aplus-fetcher:0.2
        container_name: ${APPLICATION_NAME}
        restart: "no"
        ports:
            - ${HOST_PORT}:8080
        environment:
            - APPLICATION_NAME=${APPLICATION_NAME}
            - HOST_NAME=${HOST_NAME}
            - HOST_PORT=${HOST_PORT}
            - MONGODB_HOST=${MONGODB_HOST}
            - MONGODB_PORT=${MONGODB_PORT}
            - MONGODB_USERNAME=${MONGODB_USERNAME}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
            - MONGODB_METADATA_DATABASE=${MONGODB_METADATA_DATABASE}
            - MONGODB_DATA_DATABASE=${MONGODB_DATA_DATABASE}
            - APLUS_HOST=${APLUS_HOST}
            - APLUS_TOKEN=${APLUS_TOKEN}
            - APLUS_INSECURE_CONNECTION=${APLUS_INSECURE_CONNECTION}
            - DATA_BROKER_ADDRESS=${DATA_BROKER_ADDRESS}
            - ADDITIONAL_METADATA=${ADDITIONAL_METADATA}
        volumes:
            - ./metadata_aplus.json:${ADDITIONAL_METADATA}
        networks:
            - visdom-mongodb-network

networks:
    visdom-mongodb-network:
        name: ${MONGODB_NETWORK}
        external: true
